# Generated by Django 4.2.3 on 2024-02-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cab_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_place', models.CharField(max_length=100)),
                ('drop_place', models.CharField(max_length=100)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('drop_date', models.DateField()),
                ('drop_time', models.TimeField()),
            ],
        ),
    ]
