# Generated by Django 4.2.3 on 2024-02-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cab_booking',
        ),
    ]
