# Generated by Django 4.2.3 on 2024-02-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_hotel_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=500)),
                ('Phonenumber', models.BigIntegerField()),
                ('Message', models.TextField()),
                ('Subject', models.CharField(max_length=1000)),
            ],
        ),
    ]
