# Generated by Django 4.2.3 on 2024-02-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_faqitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQItem',
            new_name='Hotel_FAQItem',
        ),
    ]
