# Generated by Django 4.2.3 on 2024-02-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_rename_faqitem_hotel_faqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photo/')),
                ('Details', models.TextField(default='', help_text='Enter each benefit point on a new line.')),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='deg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('point1', models.CharField(default='', max_length=255)),
                ('Link1', models.CharField(default='', max_length=255)),
                ('point2', models.CharField(default='', max_length=255)),
                ('Link2', models.CharField(default='', max_length=255)),
                ('point3', models.CharField(default='', max_length=255)),
                ('Link3', models.CharField(default='', max_length=255)),
                ('point4', models.CharField(default='', max_length=255)),
                ('Link4', models.CharField(default='', max_length=255)),
                ('point5', models.CharField(default='', max_length=255)),
                ('Link5', models.CharField(default='', max_length=255)),
                ('point6', models.CharField(default='', max_length=255)),
                ('Link6', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Footer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', models.ImageField(upload_to='images/')),
                ('Image2', models.ImageField(upload_to='images/')),
                ('Image3', models.ImageField(upload_to='images/')),
                ('Image4', models.ImageField(upload_to='images/')),
                ('Image5', models.ImageField(upload_to='images/')),
                ('Image6', models.ImageField(upload_to='images/')),
                ('Image7', models.ImageField(upload_to='images/')),
                ('Image8', models.ImageField(upload_to='images/')),
                ('Image9', models.ImageField(upload_to='images/')),
                ('link1', models.CharField(default='', max_length=255)),
                ('link2', models.CharField(default='', max_length=255)),
                ('link3', models.CharField(default='', max_length=255)),
                ('link4', models.CharField(default='', max_length=255)),
                ('link5', models.CharField(default='', max_length=255)),
                ('link6', models.CharField(default='', max_length=255)),
                ('link7', models.CharField(default='', max_length=255)),
                ('link8', models.CharField(default='', max_length=255)),
                ('link9', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Footer2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title1', models.CharField(default='', max_length=100)),
                ('Image1', models.ImageField(upload_to='images/')),
                ('Image2', models.ImageField(upload_to='images/')),
                ('Image3', models.ImageField(upload_to='images/')),
                ('link1', models.CharField(default='', max_length=255)),
                ('link2', models.CharField(default='', max_length=255)),
                ('link3', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Footer3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title2', models.CharField(default='', max_length=100)),
                ('contactno', models.BigIntegerField()),
                ('contactno1', models.BigIntegerField()),
                ('Title3', models.CharField(default='', max_length=100)),
                ('Emailid', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Footer4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title4', models.CharField(default='', max_length=100)),
                ('Image1', models.ImageField(upload_to='images/')),
                ('link1', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Footer5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title5', models.CharField(default='', max_length=100)),
                ('Image1', models.ImageField(upload_to='images/')),
                ('Image2', models.ImageField(upload_to='images/')),
                ('link1', models.CharField(default='', max_length=255)),
                ('link2', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Footer6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', models.ImageField(upload_to='images/')),
                ('Title6', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
