# Generated by Django 4.2.3 on 2024-02-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_blog_deg_facilities_facilities1_footer_footer1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=3000)),
            ],
        ),
    ]
