# Generated by Django 5.0.2 on 2024-02-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='card1_offerdetailes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('PromoCode', models.CharField(max_length=400)),
                ('offer', models.CharField(max_length=300)),
                ('Applicable_on', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='card1_offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('logo2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=400)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='card1_terms_conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='choosing_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'choosing_content',
            },
        ),
        migrations.CreateModel(
            name='faqs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='flight_offer_first',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='flight_offer_first1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='flight_offers7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('heading', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('point', models.TextField(default='', help_text='Enter product info on a new line.')),
            ],
        ),
        migrations.CreateModel(
            name='flight_offers8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(upload_to='images/')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='flights_offercards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('logo', models.ImageField(default=None, upload_to='images/')),
                ('url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='hdfc_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='hdfc_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='icic_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
                ('content1', models.CharField(max_length=250)),
                ('content2', models.CharField(max_length=250)),
                ('logo1', models.ImageField(blank=True, upload_to='images/')),
                ('logo2', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='icic_terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='kotak_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('text', models.CharField(max_length=100)),
                ('text1', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kotak_offer',
            },
        ),
        migrations.CreateModel(
            name='kotak_offer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='media/')),
                ('category', models.CharField(max_length=100)),
                ('couponcode', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kotak_offer1',
            },
        ),
        migrations.CreateModel(
            name='kotak_terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.TextField()),
                ('condition', models.TextField(default='')),
            ],
            options={
                'db_table': 'kotak_terms',
            },
        ),
        migrations.CreateModel(
            name='policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'policy',
            },
        ),
        migrations.CreateModel(
            name='policy1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.TextField()),
            ],
            options={
                'db_table': 'policy1',
            },
        ),
        migrations.CreateModel(
            name='sbiimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'sbiimage',
            },
        ),
        migrations.CreateModel(
            name='sbioffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=200)),
                ('min_amt', models.CharField(max_length=100)),
                ('Promo_Code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sbiterms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='why_choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zero_cancellation_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('content1', models.CharField(max_length=200)),
                ('content2', models.CharField(max_length=200)),
                ('logo1', models.ImageField(blank=True, upload_to='images/')),
                ('logo2', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Zero_cancellation_terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
