# Generated by Django 5.0.3 on 2024-03-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_card1_offerdetailes_card1_offers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='axis_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'db_table': 'axis_offer',
            },
        ),
        migrations.CreateModel(
            name='axis_offer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'axis_offer1',
            },
        ),
        migrations.CreateModel(
            name='axis_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('content3', models.TextField()),
                ('content4', models.TextField(default='')),
            ],
            options={
                'db_table': 'axis_policy',
            },
        ),
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='media/')),
                ('url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='federal_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=100)),
                ('couponcode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'federal_offer',
            },
        ),
        migrations.CreateModel(
            name='federal_offer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'federal_offer1',
            },
        ),
        migrations.CreateModel(
            name='federal_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cntnt', models.TextField()),
                ('cntnt1', models.TextField()),
            ],
            options={
                'db_table': 'federal_policy',
            },
        ),
        migrations.CreateModel(
            name='hotel_kotakoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=100)),
                ('couponcode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hotel_kotakoffer',
            },
        ),
        migrations.CreateModel(
            name='hotel_kotakoffer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hotel_kotakoffer1',
            },
        ),
        migrations.CreateModel(
            name='hotel_kotakpolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cntnt', models.TextField()),
                ('cntnt1', models.TextField()),
                ('cntnt2', models.TextField()),
                ('cntnt3', models.TextField()),
            ],
            options={
                'db_table': 'hotel_kotakpolicy',
            },
        ),
        migrations.CreateModel(
            name='hsbc_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=100)),
                ('couponcode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hsbc_offer',
            },
        ),
        migrations.CreateModel(
            name='hsbc_offer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hsbc_offer1',
            },
        ),
        migrations.CreateModel(
            name='hsbc_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('data1', models.TextField()),
                ('data2', models.TextField()),
                ('data3', models.TextField()),
                ('data4', models.TextField()),
            ],
            options={
                'db_table': 'hsbc_policy',
            },
        ),
        migrations.CreateModel(
            name='icici_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=100)),
                ('couponcode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'icici_offer',
            },
        ),
        migrations.CreateModel(
            name='icici_offer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'icici_offer1',
            },
        ),
        migrations.CreateModel(
            name='icici_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('content3', models.TextField()),
                ('content4', models.TextField(default='')),
            ],
            options={
                'db_table': 'icici_policy',
            },
        ),
        migrations.CreateModel(
            name='quary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('ans', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sbi_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=100)),
                ('couponcode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sbi_offer',
            },
        ),
        migrations.CreateModel(
            name='sbi_offer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable', models.CharField(max_length=100)),
                ('offer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sbi_offer1',
            },
        ),
        migrations.CreateModel(
            name='sbi_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.TextField()),
                ('cnt1', models.TextField()),
                ('cnt2', models.TextField()),
                ('cnt3', models.TextField()),
                ('cnt4', models.TextField()),
            ],
            options={
                'db_table': 'sbi_policy',
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='deg',
        ),
        migrations.DeleteModel(
            name='Facilities',
        ),
        migrations.DeleteModel(
            name='Facilities1',
        ),
        migrations.DeleteModel(
            name='faq',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='Footer1',
        ),
        migrations.DeleteModel(
            name='Footer2',
        ),
        migrations.DeleteModel(
            name='Footer3',
        ),
        migrations.DeleteModel(
            name='Footer4',
        ),
        migrations.DeleteModel(
            name='Footer5',
        ),
        migrations.DeleteModel(
            name='Footer6',
        ),
        migrations.DeleteModel(
            name='Hotel_FAQItem',
        ),
        migrations.DeleteModel(
            name='Hotel_offers',
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
        migrations.DeleteModel(
            name='Hotels1',
        ),
        migrations.DeleteModel(
            name='Hotels2',
        ),
    ]
