# Generated by Django 5.0.3 on 2024-04-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_anytime_cab_cards_cab_faq_cabbooking_cabwhycontents_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='anytime',
        ),
        migrations.DeleteModel(
            name='cab_cards',
        ),
        migrations.DeleteModel(
            name='cab_faq',
        ),
        migrations.DeleteModel(
            name='CabBooking',
        ),
        migrations.DeleteModel(
            name='cabwhycontents',
        ),
        migrations.DeleteModel(
            name='easy',
        ),
        migrations.DeleteModel(
            name='familyfun',
        ),
        migrations.DeleteModel(
            name='festive',
        ),
        migrations.DeleteModel(
            name='offer_card',
        ),
        migrations.DeleteModel(
            name='paytm_card',
        ),
        migrations.DeleteModel(
            name='rental',
        ),
        migrations.DeleteModel(
            name='ride',
        ),
    ]
