# Generated by Django 5.0.3 on 2024-04-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_delete_anytime_delete_cab_cards_delete_cab_faq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_offers8',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
