# Generated by Django 5.0.3 on 2024-04-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_anytime_cab_cards_cab_faq_cabbooking_cabwhycontents_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familyfun',
            new_name='cab_anytime',
        ),
        migrations.RenameModel(
            old_name='easy',
            new_name='cab_easy',
        ),
        migrations.RenameModel(
            old_name='anytime',
            new_name='cab_familyfun',
        ),
        migrations.RenameModel(
            old_name='offer_card',
            new_name='cab_festive',
        ),
        migrations.RenameModel(
            old_name='paytm_card',
            new_name='cab_offer_card',
        ),
        migrations.RenameModel(
            old_name='festive',
            new_name='cab_paytm_card',
        ),
        migrations.RenameModel(
            old_name='ride',
            new_name='cab_rental',
        ),
        migrations.RenameModel(
            old_name='rental',
            new_name='cab_ride',
        ),
        migrations.AlterModelTable(
            name='cab_rental',
            table='cab_rental',
        ),
        migrations.AlterModelTable(
            name='cab_ride',
            table=None,
        ),
    ]
