# Generated by Django 5.0.3 on 2024-04-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_bus_faq_bus_offercards_bus_trending01_bus_trending1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bus_faq',
        ),
        migrations.DeleteModel(
            name='bus_offercards',
        ),
        migrations.DeleteModel(
            name='bus_trending01',
        ),
        migrations.DeleteModel(
            name='bus_trending1',
        ),
        migrations.DeleteModel(
            name='bus_trending12',
        ),
        migrations.DeleteModel(
            name='bus_trending13',
        ),
        migrations.DeleteModel(
            name='bus_trending14',
        ),
        migrations.DeleteModel(
            name='bus_trending15',
        ),
        migrations.DeleteModel(
            name='bus_trending16',
        ),
        migrations.DeleteModel(
            name='bus_trending17',
        ),
        migrations.DeleteModel(
            name='bus_trending18',
        ),
        migrations.DeleteModel(
            name='bus_trending19',
        ),
        migrations.DeleteModel(
            name='bus_trending2',
        ),
        migrations.DeleteModel(
            name='bus_trending20',
        ),
        migrations.DeleteModel(
            name='bus_trending21',
        ),
        migrations.DeleteModel(
            name='bus_trending22',
        ),
        migrations.DeleteModel(
            name='bus_trending23',
        ),
        migrations.DeleteModel(
            name='bus_trending3',
        ),
        migrations.DeleteModel(
            name='bus_trending4',
        ),
        migrations.DeleteModel(
            name='bus_trending5',
        ),
        migrations.DeleteModel(
            name='bus_trending6',
        ),
        migrations.DeleteModel(
            name='bus_trending7',
        ),
        migrations.DeleteModel(
            name='bus_trending8',
        ),
        migrations.DeleteModel(
            name='bus_trending9',
        ),
        migrations.DeleteModel(
            name='bus_whychoose',
        ),
        migrations.DeleteModel(
            name='busfaq',
        ),
    ]
