# Generated by Django 4.2.6 on 2024-04-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_bus_special_terms4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus_go_cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('point', models.TextField(default='', help_text='Enter product info on a new line.')),
            ],
        ),
    ]
