# Generated by Django 4.2.7 on 2024-04-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='icon',
            field=models.CharField(default='', max_length=100),
        ),
    ]
