# Generated by Django 5.0.3 on 2024-06-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_delete_flight_offersupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight_crudoperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
