# Generated by Django 5.0.6 on 2024-06-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_buses_offerscrudoperations_cabs_offerscrudoperations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard_sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='sidebar',
        ),
    ]
