# Generated by Django 5.0.6 on 2024-06-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0045_buses_2ndpages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cabs_offerscrudoperations',
        ),
    ]
