# Generated by Django 5.0.6 on 2024-06-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0047_flights_2ndpages_hotels_2ndpages'),
    ]

    operations = [
        migrations.CreateModel(
            name='flights_2npdpages_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
