# Generated by Django 5.0.2 on 2024-06-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0048_flights_2npdpages_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dashboard_sidebar',
        ),
    ]
